---
linters-settings:
  gosec:
    settings:
      exclude: "G102"
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
    - github.com/sirupsen/logrus
  misspell:
    locale: US
  lll:
    line-length: 140
  funlen:
    lines: 110
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
linters:
  enable-all: true
  disable:
  - maligned
  - prealloc
  - gochecknoglobals
  - interfacer
  - dupl
run:
  skip-dirs:
  - test/testdata_etc
  - pkg/golinters/goanalysis/(checker|passes)
issues:
  exclude-rules:
  - text: weak cryptographic primitive    
    linters:
    - gosec
  - text: Binds to all network interfaces
    linters:
    - gosec
service:
  golangci-lint-version: 1.17.x
  prepare:
  - echo "here I can run custom commands, but no preparation needed for this repo"
