language: go

go:
- "1.13"

services:
  - mongodb

before_script:
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

script:
  - golangci-lint run
  - go test -v ./...

after_success:
  - go install github.com/mattn/goveralls
  - goveralls -package github.com/EreminDm/golang_basic_crud -service=travis-ci