language: go

go:
- "1.13"

# services:
#   - mongodb

addons:
  mariadb: "10.4"

# before_install:
#   - bash install-protobuf.sh

before_script:
  - mysql CREATE USER 'test'@'%' IDENTIFIED BY 'root';
  - mysql GRANT SHOW DATABASES, SELECT, PROCESS, EXECUTE, ALTER ROUTINE, ALTER, SHOW VIEW, CREATE TABLESPACE, CREATE ROUTINE, CREATE, DELETE, CREATE VIEW, CREATE TEMPORARY TABLES, INDEX, EVENT, DROP, TRIGGER, REFERENCES, INSERT, FILE, CREATE USER, UPDATE, RELOAD, LOCK TABLES, SHUTDOWN, REPLICATION SLAVE, REPLICATION CLIENT, SUPER ON *.* TO 'test'@'%';
  - mysql FLUSH PRIVILEGES;
  - mysql < db/mariadb/migrations/up/baseline.sql
  # - sleep 15
  # - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  # - go install github.com/mattn/goveralls
  # - go get -u github.com/golang/protobuf/protoc-gen-go
  # - protoc -I ./net/grpc/ grpc.proto --go_out=plugins=grpc:./net/grpc/

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -service=travis-ci -coverprofile=coverage.out
  