sudo: false
language: go
go:
- '1.13'
# dist: trusty
services:
- mysql
- mongodb
- docker
addons:
  mariadb: '10.4'
cache:
  directories:
  - "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secret.json
before_install:
- openssl aes-256-cbc -K $encrypted_bad161ded208_key -iv $encrypted_bad161ded208_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar xzf credentials.tar.gz
- if [ ! -d $HOME/gcloud/google-cloud-sdk ]; 
  then mkdir -p $HOME/gcloud && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
  --directory-prefix=$HOME/gcloud && cd $HOME/gcloud && tar xzf google-cloud-sdk.tar.gz && printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && cd $TRAVIS_BUILD_DIR;
  fi
- if [ -a client_secret.json ]; 
  then gcloud -q auth activate-service-account --key-file client_secret.json; 
  fi
before_script:
- sleep 15
- go get -v github.com/rubenv/sql-migrate/...
- make mysql
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s -- -b $(go env GOPATH)/bin v1.18.0
- go install github.com/mattn/goveralls
- go get -u github.com/golang/protobuf/protoc-gen-go
script:
- cat /etc/hosts
- golangci-lint run
- go test -covermode=count -coverprofile=coverage.out ./...
- goveralls -service=travis-ci -coverprofile=coverage.out
- ls ./
deploy:
  provider: gae
  keyfile: client_secret.json
  project: golang-basic-crud
