language: go

go:
- "1.13"

services:
  - mongodb

install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz
  - tar -xzvf protobuf-all-3.6.1.tar.gz
  - pushd protobuf-3.6.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go install github.com/mattn/goveralls
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - cd ./net/grpc/
  - protoc -I . grpc.proto --go_out=plugins=grpc:.

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -service=travis-ci -coverprofile=coverage.out
  