language: go

go:
- master

services:
  - mongodb

before_script:
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.0

script:
  - golangci-lint run
  - go test -v ./...