language: go

go:
- "1.13"

services:
  - mongodb
  - mysql

addons:
  mariadb: "10.4"
  
# before_install:
#   - bash install-protobuf.sh

before_script:
  - go get -v github.com/rubenv/sql-migrate/...
  - make mysql
  # - sudo mysql < db/mariadb/migrations/up/baseline.sql
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go install github.com/mattn/goveralls
  - go get -u github.com/golang/protobuf/protoc-gen-go 
  #- protoc -I ./net/grpc/proto grpc.proto --go_out=plugins=grpc:./net/grpc/proto

script:
  - golangci-lint run
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -service=travis-ci -coverprofile=coverage.out
  