sudo: false
language: go
go:
- '1.13'
dist: trusty
services:
- mysql
- mongodb
- docker
addons:
  mariadb: '10.4'
cache:
  directories:
  - "$HOME/google-cloud-sdk"
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_bad161ded208_key -iv $encrypted_bad161ded208_iv
  -in client-secret.json.enc -out client-secret.json -d
before_script:
- go get -v github.com/rubenv/sql-migrate/...
- make mysql
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s -- -b $(go env GOPATH)/bin v1.18.0
- go install github.com/mattn/goveralls
script:
- golangci-lint run
- go test -covermode=count -coverprofile=coverage.out ./...
after_success:
- goveralls -service=travis-ci -coverprofile=coverage.out
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  make preparekub; fi
- make gauth buildkub pushkub deploykub
