language: go

go:
- "1.13"

services:
  - mongodb
  
before_install:
  - ./install-protobuf.sh

install:
  - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd

before_script:
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go install github.com/mattn/goveralls
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - cd ./net/grpc/ && protoc -I . grpc.proto --go_out=plugins=grpc:.

script:
  - golangci-lint run
  - go test ./... -v -covermode=count -coverprofile=coverage.out.tmp
  - cat cover.out.tmp | grep -v "grpc.pb.go" > cover.out
  - tool cover -func cover.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
  