language: go

go:
- "1.13"
- master

services:
  - mongodb

before_script:
  - sleep 15
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run
  - $(go env GOPATH)/bin/goveralls -service=travis-ci
  - go test -v ./...